### ISSUE TITLE
关于baseline中使用EMA的问题

### ISSUE THREAD

**Issue by lilslsls** [jiawei151/SGIEL_VIReID#1]
您好！感谢您精彩的工作。我看到本文的baseline，Rank-1精度大约到了70左右。我去掉您的所有项，训练出来精度为67.99。但是，每个step更新参数后，也执行了EMA更新，但是ema模型最终精度为1%，而且整个训练过程中测试也没啥变化，不知道什么情况。还有就是不加ema 67.99的精度是正常的吗？

**Comment by jiawei151** [comment]
> 个step更新参数后，也执行了EMA更新，

Hi, @lilslsls ! Thanks for your interest in our work. I'm wondering whether the BN running buffers has been updated in your implementation. In our baseline implementation, Line 353-354 in `train.py` is required to make all BN running buffers up-to-date.
``` python
with torch.no_grad():
    outputs_ema = net_ema(x1, x2, x1_shape, x2_shape, y=y)
```

**Comment by lilslsls** [comment]
Thank you very much for your help. The test results during the training phase are now normal.
