### ISSUE TITLE
SYSU_MM01_SHAPE

### ISSUE THREAD

**Issue by Mrkkew** [jiawei151/SGIEL_VIReID#2]
I want to ask how to obtain SYSU_MM01_SHAPE and SYSU_MM01_MASK ?

**Comment by jiawei151** [comment]
> I want to ask how to obtain SYSU_MM01_SHAPE and SYSU_MM01_MASK ?

Hi,@Mrkkew .Please refer to 'Body Shape Data' in README, and only SYSU_MM01_SHAPE is required. We will release this dataset as soon as possible.

**Comment by Outsider-shroud** [comment]
I would like to know how to obtain the human parsing  of VCM-HIT. Is there any detailed instructions？

**Comment by jiawei151** [comment]
> I would like to know how to obtain the human parsing of VCM-HIT. Is there any detailed instructions？

Hi @Outsider-shroud . There is no difference across datasets. We utilized the same preprocessing one-to-one mapping strategy.

**Comment by Outsider-shroud** [comment]
Does infrared image generate human parsing? But the effect of Self-Correction-Human-Parsing is poor.

**Comment by jiawei151** [comment]
> Does infrared image generate human parsing? But the effect of Self-Correction-Human-Parsing is poor.

We reported this during reviewing and we will update this to appendix. Actually, they need not be too good cause they are just a guidance and not used during testing. Besides, I think it can perform better if the pretrained SCHP is tuned on infrared data, which we haven't tried yet. You may have a try if you are interested.

**Comment by jiawei151** [comment]
> Does infrared image generate human parsing? But the effect of Self-Correction-Human-Parsing is poor.

I think it can perform better if the pretrained SCHP is tuned on infrared data, which we haven't tried yet. You may have a try if you were interested. Actually, they need not be too good cause they are just a guidance and not used during testing.

**Comment by Outsider-shroud** [comment]
![vcm png](https://user-images.githubusercontent.com/84433658/234790799-beb4002c-60f9-4bff-b1ad-46c18ca00b25.jpg)
Hello, is the baseline you use only AGW? May I ask if there are any adjustments? I used the baseline（AGW） to verify that rank1 was only 53% in the HIT-VCM data set。

**Comment by jiawei151** [comment]
> 

Please refer to implementation details or our code. The baseline for 3 datasets was implemented on a ResNet50 backbone and BNNeck head with additional data augmentations.

**Comment by jiawei151** [comment]
> ![vcm png](https://user-images.githubusercontent.com/84433658/234790799-beb4002c-60f9-4bff-b1ad-46c18ca00b25.jpg) Hello, is the baseline you use only AGW? May I ask if there are any adjustments? I used the baseline（AGW） to verify that rank1 was only 53% in the HIT-VCM data set。

Please refer to implementation details or our code. The baseline for 3 datasets was implemented on a ResNet50 backbone and BNNeck head with additional data augmentations.

**Comment by Outsider-shroud** [comment]
Hi, I can't reproduce the body shape dataset, can you share this part of the code?

**Comment by Mrkkew** [comment]
Can you share your  segment body shape datasets of SYSU-MM01 and RegDB?

**Comment by jiawei151** [comment]
Hi @Mrkkew and @Outsider-shroud , we just uploaded a link for the body shape data in README.
