### ISSUE TITLE
How do you manage with failed instances??

### ISSUE THREAD

**Issue by sungmin9939** [jiawei151/SGIEL_VIReID#3]
it seems that you trained your proposed model with the shape data prepared (not generating them when training)
but when i try SCHP model on SYSU, there is a phenomenon that SCHP significantly fails on images with under certain resolution. it outputs totally nothing. how did you solve that? did you manually labeled them or use another model?

and additionally, how did you manage images that have more than 1 person? if more than 1 person exist in an image, SCHP detect all human parts.

**Comment by jiawei151** [comment]
Hello @sungmin9939 ! We didn't make a special design for this case.
