### ISSUE TITLE
body shape files 

### ISSUE THREAD

**Issue by WheatCao** [jiawei151/SGIEL_VIReID#7]
Could you share your .npy files for the body shape of  SYSU-MM01 and RegDB datasets?

**Comment by jiawei151** [comment]
Hi @WheatCao ! We just uploaded a link for the body shape data of SYSU-MM01 in README.

**Comment by WheatCao** [comment]
> Hi @WheatCao ! We just uploaded a link for the body shape data of SYSU-MM01 in README.

Thanks for your outstanding work :)
