### ISSUE TITLE
data_path路径咨询

### ISSUE THREAD

**Issue by dxzjnyy** [jiawei151/SGIEL_VIReID#8]
我想问一下，data_path1里面是您分享的shape数据集，data_path2文件夹下放的是什么呢？

**Comment by jiawei151** [comment]
> 我想问一下，data_path1里面是您分享的shape数据集，data_path2文件夹下放的是什么呢？

@dxzjnyy 你好，这里是没有用到的代码，是我没有清理干净，请忽略就行。

**Comment by dxzjnyy** [comment]
明白啦，谢谢
